[package]
name = "serverless-with-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.17.0", features = ["macros"] }
serde_json = "1.0"
lambda_runtime = { version = "0.5.1" }
lambda_http = { version = "0.5.1" }
